spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
#    initialize: true
#    sql-script-encoding: UTF-8
    url: jdbc:mysql://localhost:3306/cookbook
    username: root
    password: 12345678
